### ISSUE TITLE
A站客户端

### ISSUE THREAD

**Issue by Harlber** [succlz123/AxBTube#1]
好巧，今天才看到这个，你这个项目比我早一个月, 我的项目地址(https://github.com/Harlber/Moose)  ,大致看了下，material design 部分貌似分量不够重，功能比我那个多好多，赞一个。Btw，Retrofit，okthhp之类可以升级了。

**Comment by SiBorya** [comment]
话说为啥突然改名成BlueBoard了

**Comment by succlz123** [comment]
@Kroderia 因为被google按在地上摩擦了（上架google play的时候，因为色情原因被误封了）所以要改包名。
