### ISSUE TITLE
请求添加播放逻辑控制，如seek、pause、resume等，谢谢

### ISSUE THREAD

**Issue by windrunnerlihuan** [succlz123/AxBTube#7]
您好，
         您在VideoPlayActivity里没有做播放控制逻辑，一些回调没有添加。但是您之前的一个项目okplayer的播放回调基于android 系统的mediacontroller，这个项目可能需要自定义这些回调动作，麻烦大神加上这些，给我们一个学习的机会，谢谢！

**Comment by succlz123** [comment]
@li937874128 其实是有的，你可以参考下这个buleboard。最近没什么时间来写这么详细的使用方法。
